site_general:
    resource: "@SiteGeneralBundle/Resources/config/routing.yml"
    prefix:   /

site_user:
    resource: "@SiteUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site_article:
    resource: "@SiteArticleBundle/Resources/config/routing.yml"
    prefix:   /article

site_form:
    resource: "@SiteFormBundle/Resources/config/routing.yml"
    prefix:   /forum
