blog_blog:
    resource: "@BlogBlogBundle/Resources/config/routing.yml"
    prefix:   /

blog_user:
    resource: "@BlogUserBundle/Resources/config/routing.yml"
    prefix:   /

blog_general:
    resource: "@BlogGeneralBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
