post:
    path:     /
    defaults: { _controller: "BlogBlogBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBlogBundle:Post:show" }

post_new:
    path:     /new
    defaults: { _controller: "BlogBlogBundle:Post:new" }

post_create:
    path:     /create
    defaults: { _controller: "BlogBlogBundle:Post:create" }
    methods:  POST

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBlogBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "BlogBlogBundle:Post:update" }
    methods:  [POST, PUT]

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBlogBundle:Post:delete" }
    methods:  [POST, DELETE]
